build time -- 2022-07-03 02:54:13.398215

Inactive Modules:
  1) mpt/2.25

Due to MODULEPATH changes, the following have been reloaded:
  1) ncarcompilers/0.5.0

The following have been reloaded with a version change:
  1) intel/19.1.1 => intel/18.0.5     2) netcdf/4.8.1 => netcdf/4.6.3

+ export ESMF_NETCDF=nc-config
+ ESMF_NETCDF=nc-config
+ export ESMF_DIR=/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop
+ ESMF_DIR=/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop
+ export ESMF_COMPILER=intel
+ ESMF_COMPILER=intel
+ export ESMF_COMM=intelmpi
+ ESMF_COMM=intelmpi
+ export ESMF_BOPT=g
+ ESMF_BOPT=g
+ export ESMF_TESTEXHAUSTIVE=ON
+ ESMF_TESTEXHAUSTIVE=ON
+ export ESMF_TESTWITHTHREADS=ON
+ ESMF_TESTWITHTHREADS=ON
+ python3 setup.py test_examples_dryrun
running test_examples_dryrun
Traceback (most recent call last):
  File "src/ESMF/interface/loadESMF.py", line 134, in <module>
    mode=ct.RTLD_GLOBAL)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Linux.intel.64.intelmpi.default/libesmf_fullylinked.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "src/ESMF/interface/loadESMF.py", line 134, in <module>
    mode=ct.RTLD_GLOBAL)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Linux.intel.64.intelmpi.default/libesmf_fullylinked.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 278, in <module>
    'test_regrid_from_file_parallel': TestRegridFromFileParallelCommand})
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 13, in wrapper
    from ESMF.util.cache_data import cache_data_files
  File "src/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "src/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "src/ESMF/interface/cbindings.py", line 13, in <module>
    from ESMF.interface.loadESMF import _ESMF
  File "src/ESMF/interface/loadESMF.py", line 137, in <module>
    raise ImportError('The ESMF shared library did not load properly.')
ImportError: The ESMF shared library did not load properly.
+ python3 setup.py test_regrid_from_file_dryrun
running test_regrid_from_file_dryrun
Traceback (most recent call last):
  File "/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop/src/addon/ESMPy/src/ESMF/interface/loadESMF.py", line 134, in <module>
    mode=ct.RTLD_GLOBAL)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Linux.intel.64.intelmpi.default/libesmf_fullylinked.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop/src/addon/ESMPy/src/ESMF/interface/loadESMF.py", line 134, in <module>
    mode=ct.RTLD_GLOBAL)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop/DEFAULTINSTALLDIR/lib/libg/Linux.intel.64.intelmpi.default/libesmf_fullylinked.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/ESMF/test/regrid_from_file/run_regrid_from_file_dryrun.py", line 14, in <module>
    from ESMF.test.regrid_from_file.regrid_from_file_consts import DATA_SUBDIR, DATA_URL_ROOT
  File "/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop/src/addon/ESMPy/src/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop/src/addon/ESMPy/src/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop/src/addon/ESMPy/src/ESMF/interface/cbindings.py", line 13, in <module>
    from ESMF.interface.loadESMF import _ESMF
  File "/glade/scratch/dunlap/esmf-testing/intel_18.0.5_intelmpi_g_develop/src/addon/ESMPy/src/ESMF/interface/loadESMF.py", line 137, in <module>
    raise ImportError('The ESMF shared library did not load properly.')
ImportError: The ESMF shared library did not load properly.
Traceback (most recent call last):
  File "setup.py", line 278, in <module>
    'test_regrid_from_file_parallel': TestRegridFromFileParallelCommand})
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 197, in run
    subprocess.check_call(cmd)
  File "/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/glade/u/apps/ch/opt/python/3.7.9/gnu/9.1.0/bin/python3', 'src/ESMF/test/regrid_from_file/run_regrid_from_file_dryrun.py']' returned non-zero exit status 1.
