build time -- 14:04:15
running test
Failure: IOError ([Errno 2] No such file or directory: '') ... ERROR

======================================================================
ERROR: Failure: IOError ([Errno 2] No such file or directory: '')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/scratch1/NCEPDEV/stmp2/role.esmfmaint/gfortran_9.2.0b_openmpi_g_develop/src/addon/ESMPy/src/ESMF/__init__.py", line 69, in <module>
    from ESMF.api.esmpymanager import *
  File "/scratch1/NCEPDEV/stmp2/role.esmfmaint/gfortran_9.2.0b_openmpi_g_develop/src/addon/ESMPy/src/ESMF/api/esmpymanager.py", line 11, in <module>
    from ESMF.interface.cbindings import *
  File "/scratch1/NCEPDEV/stmp2/role.esmfmaint/gfortran_9.2.0b_openmpi_g_develop/src/addon/ESMPy/src/ESMF/interface/cbindings.py", line 13, in <module>
    from ESMF.interface.loadESMF import _ESMF
  File "/scratch1/NCEPDEV/stmp2/role.esmfmaint/gfortran_9.2.0b_openmpi_g_develop/src/addon/ESMPy/src/ESMF/interface/loadESMF.py", line 36, in <module>
    with open(esmfmk, 'r') as MKFILE:
IOError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
XML: /scratch1/NCEPDEV/stmp2/role.esmfmaint/gfortran_9.2.0b_openmpi_g_develop/src/addon/ESMPy/nosetests.xml
----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/stmp2/role.esmfmaint/gfortran_9.2.0b_openmpi_g_develop/src/addon/ESMPy/setup.py", line 249, in <module>
    setup(name="ESMPy",
  File "/apps/oneapi/intelpython/latest/envs/2022.0.2/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/apps/oneapi/intelpython/latest/envs/2022.0.2/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/apps/oneapi/intelpython/latest/envs/2022.0.2/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/scratch1/NCEPDEV/stmp2/role.esmfmaint/gfortran_9.2.0b_openmpi_g_develop/src/addon/ESMPy/setup.py", line 49, in run
    subprocess.check_call(cmd)
  File "/apps/oneapi/intelpython/latest/envs/2022.0.2/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nosetests', '-vs', '--with-xunit', '-a', '!slow,!parallel', 'src/ESMF']' returned non-zero exit status 1.
